services:
  - type: web
    name: cyiza-faida-josue-cv
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
      - key: PORT
        value: 3000
